//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace Recipes-Databse-Code
{


	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>Category</summary>
		CategoryEntity,
		///<summary>Recipe</summary>
		RecipeEntity,
		///<summary>RecipeCategory</summary>
		RecipeCategoryEntity,
		///<summary>RecipeIngredient</summary>
		RecipeIngredientEntity,
		///<summary>RecipeInstruction</summary>
		RecipeInstructionEntity,
		///<summary>User</summary>
		UserEntity
	}



	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END


}

