//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using RecipeDB.HelperClasses;
using RecipeDB.FactoryClasses;
using RecipeDB.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace RecipeDB.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'RecipeIngredient'.<br/><br/></summary>
	[Serializable]
	public partial class RecipeIngredientEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private RecipeEntity _recipe;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static RecipeIngredientEntityStaticMetaData _staticMetaData = new RecipeIngredientEntityStaticMetaData();
		private static RecipeIngredientRelations _relationsFactory = new RecipeIngredientRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Recipe</summary>
			public static readonly string Recipe = "Recipe";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class RecipeIngredientEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public RecipeIngredientEntityStaticMetaData()
			{
				SetEntityCoreInfo("RecipeIngredientEntity", InheritanceHierarchyType.None, false, (int)RecipeDB.EntityType.RecipeIngredientEntity, typeof(RecipeIngredientEntity), typeof(RecipeIngredientEntityFactory), false);
				AddNavigatorMetaData<RecipeIngredientEntity, RecipeEntity>("Recipe", "RecipeIngredients", (a, b) => a._recipe = b, a => a._recipe, (a, b) => a.Recipe = b, RecipeDB.RelationClasses.StaticRecipeIngredientRelations.RecipeEntityUsingRecipeIdStatic, ()=>new RecipeIngredientRelations().RecipeEntityUsingRecipeId, null, new int[] { (int)RecipeIngredientFieldIndex.RecipeId }, null, true, (int)RecipeDB.EntityType.RecipeEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static RecipeIngredientEntity()
		{
		}

		/// <summary> CTor</summary>
		public RecipeIngredientEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public RecipeIngredientEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this RecipeIngredientEntity</param>
		public RecipeIngredientEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for RecipeIngredient which data should be fetched into this RecipeIngredient object</param>
		public RecipeIngredientEntity(System.String id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for RecipeIngredient which data should be fetched into this RecipeIngredient object</param>
		/// <param name="validator">The custom validator object for this RecipeIngredientEntity</param>
		public RecipeIngredientEntity(System.String id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected RecipeIngredientEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Recipe' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoRecipe() { return CreateRelationInfoForNavigator("Recipe"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this RecipeIngredientEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static RecipeIngredientRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Recipe' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathRecipe { get { return _staticMetaData.GetPrefetchPathElement("Recipe", CommonEntityBase.CreateEntityCollection<RecipeEntity>()); } }

		/// <summary>The Id property of the Entity RecipeIngredient<br/><br/></summary>
		/// <remarks>Mapped on  table field: "RecipeIngredients"."id".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String Id
		{
			get { return (System.String)GetValue((int)RecipeIngredientFieldIndex.Id, true); }
			set	{ SetValue((int)RecipeIngredientFieldIndex.Id, value); }
		}

		/// <summary>The Ingredient property of the Entity RecipeIngredient<br/><br/></summary>
		/// <remarks>Mapped on  table field: "RecipeIngredients"."ingredient".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 1000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Ingredient
		{
			get { return (System.String)GetValue((int)RecipeIngredientFieldIndex.Ingredient, true); }
			set	{ SetValue((int)RecipeIngredientFieldIndex.Ingredient, value); }
		}

		/// <summary>The IsActive property of the Entity RecipeIngredient<br/><br/></summary>
		/// <remarks>Mapped on  table field: "RecipeIngredients"."is_active".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsActive
		{
			get { return (System.Boolean)GetValue((int)RecipeIngredientFieldIndex.IsActive, true); }
			set	{ SetValue((int)RecipeIngredientFieldIndex.IsActive, value); }
		}

		/// <summary>The RecipeId property of the Entity RecipeIngredient<br/><br/></summary>
		/// <remarks>Mapped on  table field: "RecipeIngredients"."recipe_id".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String RecipeId
		{
			get { return (System.String)GetValue((int)RecipeIngredientFieldIndex.RecipeId, true); }
			set	{ SetValue((int)RecipeIngredientFieldIndex.RecipeId, value); }
		}

		/// <summary>Gets / sets related entity of type 'RecipeEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual RecipeEntity Recipe
		{
			get { return _recipe; }
			set { SetSingleRelatedEntityNavigator(value, "Recipe"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace RecipeDB
{
	public enum RecipeIngredientFieldIndex
	{
		///<summary>Id. </summary>
		Id,
		///<summary>Ingredient. </summary>
		Ingredient,
		///<summary>IsActive. </summary>
		IsActive,
		///<summary>RecipeId. </summary>
		RecipeId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace RecipeDB.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: RecipeIngredient. </summary>
	public partial class RecipeIngredientRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between RecipeIngredientEntity and RecipeEntity over the m:1 relation they have, using the relation between the fields: RecipeIngredient.RecipeId - Recipe.Id</summary>
		public virtual IEntityRelation RecipeEntityUsingRecipeId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Recipe", false, new[] { RecipeFields.Id, RecipeIngredientFields.RecipeId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticRecipeIngredientRelations
	{
		internal static readonly IEntityRelation RecipeEntityUsingRecipeIdStatic = new RecipeIngredientRelations().RecipeEntityUsingRecipeId;

		/// <summary>CTor</summary>
		static StaticRecipeIngredientRelations() { }
	}
}
