//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using Recipes-Databse-Code.FactoryClasses;
using Recipes-Databse-Code.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Recipes-Databse-Code.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitCategoryEntityInfo();
			InitRecipeEntityInfo();
			InitRecipeCategoryEntityInfo();
			InitRecipeIngredientEntityInfo();
			InitRecipeInstructionEntityInfo();
			InitUserEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits CategoryEntity's info objects</summary>
		private void InitCategoryEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CategoryFieldIndex), "CategoryEntity");
			this.AddElementFieldInfo("CategoryEntity", "CategoryName", typeof(System.String), true, false, false, false,  (int)CategoryFieldIndex.CategoryName, 1073741824, 0, 0);
			this.AddElementFieldInfo("CategoryEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)CategoryFieldIndex.IsActive, 0, 0, 0);
		}

		/// <summary>Inits RecipeEntity's info objects</summary>
		private void InitRecipeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RecipeFieldIndex), "RecipeEntity");
			this.AddElementFieldInfo("RecipeEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)RecipeFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("RecipeEntity", "ImagePath", typeof(System.String), false, false, false, false,  (int)RecipeFieldIndex.ImagePath, 1073741824, 0, 0);
			this.AddElementFieldInfo("RecipeEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)RecipeFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("RecipeEntity", "Title", typeof(System.String), false, false, false, false,  (int)RecipeFieldIndex.Title, 1073741824, 0, 0);
		}

		/// <summary>Inits RecipeCategoryEntity's info objects</summary>
		private void InitRecipeCategoryEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RecipeCategoryFieldIndex), "RecipeCategoryEntity");
			this.AddElementFieldInfo("RecipeCategoryEntity", "Category", typeof(System.String), false, false, false, false,  (int)RecipeCategoryFieldIndex.Category, 1000, 0, 0);
			this.AddElementFieldInfo("RecipeCategoryEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)RecipeCategoryFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("RecipeCategoryEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)RecipeCategoryFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("RecipeCategoryEntity", "RecipeId", typeof(System.Guid), false, true, false, false,  (int)RecipeCategoryFieldIndex.RecipeId, 0, 0, 0);
		}

		/// <summary>Inits RecipeIngredientEntity's info objects</summary>
		private void InitRecipeIngredientEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RecipeIngredientFieldIndex), "RecipeIngredientEntity");
			this.AddElementFieldInfo("RecipeIngredientEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)RecipeIngredientFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("RecipeIngredientEntity", "Ingredient", typeof(System.String), false, false, false, false,  (int)RecipeIngredientFieldIndex.Ingredient, 1000, 0, 0);
			this.AddElementFieldInfo("RecipeIngredientEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)RecipeIngredientFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("RecipeIngredientEntity", "RecipeId", typeof(System.Guid), false, true, false, false,  (int)RecipeIngredientFieldIndex.RecipeId, 0, 0, 0);
		}

		/// <summary>Inits RecipeInstructionEntity's info objects</summary>
		private void InitRecipeInstructionEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RecipeInstructionFieldIndex), "RecipeInstructionEntity");
			this.AddElementFieldInfo("RecipeInstructionEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)RecipeInstructionFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("RecipeInstructionEntity", "Instruction", typeof(System.String), false, false, false, false,  (int)RecipeInstructionFieldIndex.Instruction, 1000, 0, 0);
			this.AddElementFieldInfo("RecipeInstructionEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)RecipeInstructionFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("RecipeInstructionEntity", "RecipeId", typeof(System.Guid), false, true, false, false,  (int)RecipeInstructionFieldIndex.RecipeId, 0, 0, 0);
		}

		/// <summary>Inits UserEntity's info objects</summary>
		private void InitUserEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(UserFieldIndex), "UserEntity");
			this.AddElementFieldInfo("UserEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)UserFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)UserFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "PasswordHash", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.PasswordHash, 1073741824, 0, 0);
			this.AddElementFieldInfo("UserEntity", "PasswordSalt", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.PasswordSalt, 1073741824, 0, 0);
			this.AddElementFieldInfo("UserEntity", "RefreshToken", typeof(System.String), false, false, false, true,  (int)UserFieldIndex.RefreshToken, 1073741824, 0, 0);
			this.AddElementFieldInfo("UserEntity", "TokenCreated", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)UserFieldIndex.TokenCreated, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "TokenExpires", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)UserFieldIndex.TokenExpires, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Username", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Username, 1073741824, 0, 0);
		}
	}
}