//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Recipes-Databse-Code.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitCategoryEntityMappings();
			InitRecipeEntityMappings();
			InitRecipeCategoryEntityMappings();
			InitRecipeIngredientEntityMappings();
			InitRecipeInstructionEntityMappings();
			InitUserEntityMappings();
		}

		/// <summary>Inits CategoryEntity's mappings</summary>
		private void InitCategoryEntityMappings()
		{
			this.AddElementMapping("CategoryEntity", @"Recipes", @"public", "Category", 2, 0);
			this.AddElementFieldMapping("CategoryEntity", "CategoryName", "category_name", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("CategoryEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 1);
		}

		/// <summary>Inits RecipeEntity's mappings</summary>
		private void InitRecipeEntityMappings()
		{
			this.AddElementMapping("RecipeEntity", @"Recipes", @"public", "Recipe", 4, 0);
			this.AddElementFieldMapping("RecipeEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("RecipeEntity", "ImagePath", "image_path", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("RecipeEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 2);
			this.AddElementFieldMapping("RecipeEntity", "Title", "title", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits RecipeCategoryEntity's mappings</summary>
		private void InitRecipeCategoryEntityMappings()
		{
			this.AddElementMapping("RecipeCategoryEntity", @"Recipes", @"public", "RecipeCategories", 4, 0);
			this.AddElementFieldMapping("RecipeCategoryEntity", "Category", "category", false, "Varchar", 1000, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("RecipeCategoryEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 1);
			this.AddElementFieldMapping("RecipeCategoryEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 2);
			this.AddElementFieldMapping("RecipeCategoryEntity", "RecipeId", "recipe_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 3);
		}

		/// <summary>Inits RecipeIngredientEntity's mappings</summary>
		private void InitRecipeIngredientEntityMappings()
		{
			this.AddElementMapping("RecipeIngredientEntity", @"Recipes", @"public", "RecipeIngredients", 4, 0);
			this.AddElementFieldMapping("RecipeIngredientEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("RecipeIngredientEntity", "Ingredient", "ingredient", false, "Varchar", 1000, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("RecipeIngredientEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 2);
			this.AddElementFieldMapping("RecipeIngredientEntity", "RecipeId", "recipe_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 3);
		}

		/// <summary>Inits RecipeInstructionEntity's mappings</summary>
		private void InitRecipeInstructionEntityMappings()
		{
			this.AddElementMapping("RecipeInstructionEntity", @"Recipes", @"public", "RecipeInstructions", 4, 0);
			this.AddElementFieldMapping("RecipeInstructionEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("RecipeInstructionEntity", "Instruction", "instruction", false, "Varchar", 1000, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("RecipeInstructionEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 2);
			this.AddElementFieldMapping("RecipeInstructionEntity", "RecipeId", "recipe_id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 3);
		}

		/// <summary>Inits UserEntity's mappings</summary>
		private void InitUserEntityMappings()
		{
			this.AddElementMapping("UserEntity", @"Recipes", @"public", "User", 8, 0);
			this.AddElementFieldMapping("UserEntity", "Id", "id", false, "Uuid", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("UserEntity", "IsActive", "is_active", false, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 1);
			this.AddElementFieldMapping("UserEntity", "PasswordHash", "password_hash", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("UserEntity", "PasswordSalt", "password_salt", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("UserEntity", "RefreshToken", "refresh_token", true, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("UserEntity", "TokenCreated", "token_created", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 5);
			this.AddElementFieldMapping("UserEntity", "TokenExpires", "token_expires", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 6);
			this.AddElementFieldMapping("UserEntity", "Username", "username", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 7);
		}

	}
}
